### ISSUE TITLE
 how do I open this API interface to others for use

### ISSUE THREAD

**Issue by hsfzmsn** [decoy/PingPongr#13]
Hi, how do I open this API interface to others for use, I use another domain name to access, the prompt is wrong, can you tell me, thank you

**Comment by hsfzmsn** [comment]
Is how to cross domain access

**Comment by decoy** [comment]
Hello!  PingPongr doesn't do anything with domains.  That's generally handled by the host (Kestrel, IIS, nginx, or whatever you put in front of your .NET application).  Luckily, that should make it easier to find instructions specific to your hosting.

Good luck!
