### ISSUE TITLE
Owin + ApiController + Mediatr

### ISSUE THREAD

**Issue by nskerl** [decoy/PingPongr#2]
Hi there, 
Have you any experience wiring up mediatr in a more general webapi / selfhost application? PingPongr looks cool and is very close, but just curious if youve actually dealt with injecting an IMediator into an ApiController?  So much noise on the net, hard to find clear direction.

**Comment by decoy** [comment]
The original MediatR announcement shows a controller using it:  https://lostechies.com/jimmybogard/2014/12/17/mediatr-hits-1-0/

Basically you setup webapi like normal with your favorite IoC container.  Once you have webapi working in general, you can use the mediatr samples projects to show how you'd configure your handlers and decorators and such with various containers: https://github.com/jbogard/MediatR/tree/master/samples.  Mediatr is then injected into the constructor like any other dependency and then called from the individual controller functions.  

I created pingpongr to play with the idea of removing the controller (and the rest of the webapi framework) from this setup.  In my own use of mediatr, the controllers ended up just directly calling mediatr and returning the results with nothing else happening.  (All json webservices, no views, and I wasn't using any fancy routing either.)

Hope this helps!

**Comment by nskerl** [comment]
Thanks a lot, it does help!
